version: "3.9"

# psql -U postgres -d pr-reviewers-service
# \dt

services:

  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./metrics/prometheus:/etc/prometheus"
    networks:
      - app_network

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    links:
      - prometheus:prometheus
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app_network

  pr-reviewers-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-reviewers-service_app_container
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@pr-reviewers-service-db:5432/pr-reviewers-service
    restart: unless-stopped
    depends_on:
      pr-reviewers-service-db:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/myapp
    networks:
      - app_network
    ports:
      - "8080:8080"
      - "3000:3000"

  pr-reviewers-service-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pr-reviewers-service
      - POSTGRES_HOST_AUTH_METHOD=md5
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pr-reviewers-service" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_network
    expose:
      - "5432"

  k6-load-test:
    image: grafana/k6:latest
    container_name: k6-load-test
    volumes:
      - ./test/k6/scripts:/scripts
    networks:
      - app_network
    depends_on:
      - pr-reviewers-service
    restart: "no"
    command: run /scripts/pr_reviewers_loadtest.js

networks:
  app_network:
    name: app_network
