server:
  rest:
    address: :8080
    conn_settings:
      read_timeout: 5s
      write_timeout: 5s
      idle_timeout: 5m
postgres:
  conn: postgres://postgres:postgres@localhost:5432/pr-reviewers-service
  pool_settings:
    max_conns: 100
    min_idle_conns: 20
    max_conn_idle_time: 5m
    max_conn_lifetime: 10m
  migrations_dir: ./migrations
app:
#  allowed_users:
#    - user
#    - admin
  max_pr_reviewers: 2
  authorisation_needed: false # "true"
  jwt_secret: 6a627a7fb025e2c5bed303316a3a1c801c1178bed303316a627a7fb67523a1c8
  logging:
    output: "stdout" # "stdout", "stderr", "/var/log/myapp/<file.log>"
    level: "info"   # "debug", "info", "warn", "error"